services:
  skin_ai:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/dinis-a/skin_ai:latest
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "-f", "main.py"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s
